from turtle import Turtle, Screen
from random import randrange
from webcolors import rgb_to_name
angle = 360
turtle = Turtle()

for i in range(10):
    if i == 3:
        r = randrange(255)
        g = randrange(255)
        b = randrange(255)
        print(rgb_to_name(rgb_triplet= (r, g, b)))
        turtle.forward(100)
        turtle.right(angle / 3)
        turtle.forward(100)
        turtle.right(angle / 3)
        turtle.forward(100)
        turtle.right(angle / 3)
    elif i == 4:
        turtle.forward(100)
        turtle.right(angle / 4)
        turtle.forward(100)
        turtle.right(angle / 4)
        turtle.forward(100)
        turtle.right(angle / 4)
        turtle.forward(100)
        turtle.right(angle / 4)
    elif i == 5:
        turtle.forward(100)
        turtle.right(angle / 5)
        turtle.forward(100)
        turtle.right(angle / 5)
        turtle.forward(100)
        turtle.right(angle / 5)
        turtle.forward(100)
        turtle.right(angle / 5)
        turtle.forward(100)
        turtle.right(angle / 5)
    elif i == 6:
        turtle.forward(100)
        turtle.right(angle / 6)
        turtle.forward(100)
        turtle.right(angle / 6)
        turtle.forward(100)
        turtle.right(angle / 6)
        turtle.forward(100)
        turtle.right(angle / 6)
        turtle.forward(100)
        turtle.right(angle / 6)
        turtle.forward(100)
        turtle.right(angle / 6)
    elif i == 7:
        turtle.forward(100)
        turtle.right(angle / 7)
        turtle.forward(100)
        turtle.right(angle / 7)
        turtle.forward(100)
        turtle.right(angle / 7)
        turtle.forward(100)
        turtle.right(angle / 7)
        turtle.forward(100)
        turtle.right(angle / 7)
        turtle.forward(100)
        turtle.right(angle / 7)
        turtle.forward(100)
        turtle.right(angle / 7)
    elif i == 8:
        turtle.forward(100)
        turtle.right(angle / 8)
        turtle.forward(100)
        turtle.right(angle / 8)
        turtle.forward(100)
        turtle.right(angle / 8)
        turtle.forward(100)
        turtle.right(angle / 8)
        turtle.forward(100)
        turtle.right(angle / 8)
        turtle.forward(100)
        turtle.right(angle / 8)
        turtle.forward(100)
        turtle.right(angle / 8)
        turtle.forward(100)
        turtle.right(angle / 8)
    elif i == 9:
        turtle.forward(100)
        turtle.right(angle / 9)
        turtle.forward(100)
        turtle.right(angle / 9)
        turtle.forward(100)
        turtle.right(angle / 9)
        turtle.forward(100)
        turtle.right(angle / 9)
        turtle.forward(100)
        turtle.right(angle / 9)
        turtle.forward(100)
        turtle.right(angle / 9)
        turtle.forward(100)
        turtle.right(angle / 9)
        turtle.forward(100)
        turtle.right(angle / 9)
        turtle.forward(100)
        turtle.right(angle / 9)
    elif i == 10:
        turtle.forward(100)
        turtle.right(angle / 10)
        turtle.forward(100)
        turtle.right(angle / 10)
        turtle.forward(100)
        turtle.right(angle / 10)
        turtle.forward(100)
        turtle.right(angle / 10)
        turtle.forward(100)
        turtle.right(angle / 10)
        turtle.forward(100)
        turtle.right(angle / 10)
        turtle.forward(100)
        turtle.right(angle / 10)
        turtle.forward(100)
        turtle.right(angle / 10)
        turtle.forward(100)
        turtle.right(angle / 10)
        turtle.forward(100)
        turtle.right(angle / 10)

screen = Screen()
screen.exitonclick()
